### ISSUE TITLE
how to quit a session

### ISSUE THREAD

**Issue by dog-2** [nodauf/Girsh#43]
how to quit a sesions after connecting into it?

`background` command shown in the demo gif did not work.

**Comment by nodauf** [comment]
Could you please try with the new commit.
This should fix a bug if you used the backspace character inside the `background` command

**Comment by dog-2** [comment]
> Could you please try with the new commit. This should fix a bug if you used the backspace character inside the `background` command

Thx for your reply and sorry for my late reply. I've tried the new commit and it works well now. Great job! Thank you  very much!
