### ISSUE TITLE
Windows version close connections

### ISSUE THREAD

**Issue by ampf27** [nodauf/Girsh#49]
I have tried Girsh on linux and it worked just fine but when trying on Windows, I can get a sessions but after a few seconds on Girsh console I get

```
Girsh> Connect from TARGET_IP:IP
exec: "stty": executable file not found in %PATH%
exit status 1
```

While on the the other PC I get

```
Exception calling "Read" with "3" argument(s): "Unable to read data from the transport connection: An existing
connection was forcibly closed by the remote host."
At line:1 char:140
+ ... 65535|%{0};while(($i = $stream.Read($bytes, 0, $bytes.Length)) -ne 0) ...
+                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : IOException

```

I have tried with both compiled version and go but got the same result. 

What may be causing this?

**Comment by nodauf** [comment]
It should be ok with the last commit

**Comment by ampf27** [comment]
Thank you for let me know that

I will then take it account and use it on linux environment

Great work on this tool
